In [1]:
# Numpy
Data -> vectors(arrays) of numbers
Computer understands Binary ->

# Scalar - 12

# vector - 1D array - a -> [0.1, 0.2, 0.3,0.4] * 5

# matrix -> 2D Array - row, columns

# Tensors -> multi 2d array

1

In [2]:
lst = [10, 20, 30, 40]
[ele*2 for ele in lst]

[20, 40, 60, 80]

In [4]:
import array
my_arr = array.array('i', [1, 2, 3, 4, 5])
print(my_arr, type(my_arr))
print(my_arr*2)

array('i', [1, 2, 3, 4, 5]) <class 'array.array'>
array('i', [1, 2, 3, 4, 5, 1, 2, 3, 4, 5])


In [ ]:
# 1. Lists are highly flexible. -
# 2. Arrays provide better performance - Collection of homogeneous data

# List - Heterogeneous, Array - homogeneous
# List - Less Effiecient, Arrays - Efficient
# List - Slow in mathematical operations, Arrays - faster in mathematical operations(vectorized)

In [5]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr1*2

array([ 2,  4,  6,  8, 10])

In [ ]:
# Limitation of the array is - it works with one dimensional array only
# Numpy allows you to work with multidimensional array

# Pandas, Scikitlearn, Matplotlib, seaborn, tensorflow - Numpy

In [6]:
import numpy as np

In [7]:
# Creating an array out of list from homogeneous elements
arr = np.array([10, 20, 30, 40, 50])
print(arr, type(arr))


# ndarray - Multidimensional array

[10 20 30 40 50] <class 'numpy.ndarray'>


In [8]:
# Array is a collection of homogeneous elements
print(arr.dtype)       # What kind of data you have inside the array

int64


In [9]:
arr1 = np.array([10.0, 20, 30, 40, 50])
print(arr1, type(arr1))

[10. 20. 30. 40. 50.] <class 'numpy.ndarray'>


In [10]:
# Type of elements of the array
print(arr1.dtype)

float64


In [31]:
arr1.shape

(5,)

In [12]:
# Size of an array - total no of elements inside the array
print(arr1.size)

5


In [14]:
# Dimension of the array    - Gives te number of dimension of the array
print(arr1.ndim)

1


In [16]:
# Number of bytes taken by array to store all elements in the array
arr1.nbytes

40

In [ ]:
# Upcasting
# Object
# String
# Complex
# Float
# int

In [22]:
# Creating an array with heterogeneous elements
arr2 = np.array([10,20,30,40,50, 60.70, 80+90j])
print(arr2)
print(arr2.dtype)

[10.  +0.j 20.  +0.j 30.  +0.j 40.  +0.j 50.  +0.j 60.7 +0.j 80. +90.j]
complex128


In [18]:
# Creating an array with heterogeneous elements
arr3 = np.array((10,20,30,40,50, 60.70, 80+90j, '100'))
print(arr3)
print(arr3.dtype)

['10' '20' '30' '40' '50' '60.7' '(80+90j)' '100']
<U64


In [20]:
# Creating an array with heterogeneous elements
arr4 = np.array([10,20,30,40,50, 60.70, 80+90j, '100', [110, 20]], dtype = object)
print(arr4)
print(arr4.dtype)

# VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences
#  (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes)
#  is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.

[10 20 30 40 50 60.7 (80+90j) '100' list([110, 20])]
object


In [23]:
# Creating 2D array
arr5 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
type(arr5)

numpy.ndarray

In [25]:
arr5.dtype

dtype('int64')

In [27]:
arr6 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]], dtype = object)
arr6.ndim

2

In [28]:
arr6 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8]], dtype = object)
arr6.ndim

1

In [29]:
arr5.size

9

In [30]:
arr5.shape

(3, 3)

In [32]:
# (row, col)

arr1

# For one dimensioanl array, when we check shape -> (no_of_ele, ) -> (1, no_of_ele)

array([10., 20., 30., 40., 50.])

In [ ]:
array([10,
       20,
       30,
       40,
       50])

In [34]:
# arr1.shape

In [35]:
# Functions to create an array

# arange(start, stop, step)

# Arange can take a fractional value as step whereas range can take only integer value

arr1 = np.arange(10, 21)
arr1


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
arr1 = np.arange(10, 21, 0.5)
print(arr1)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5]


In [38]:
arr1 = np.arange(10, 21, 0.3)
print(arr1)

37


In [39]:
# I want to generate an array of 100 numbers in the same range?
# linspace(start, stop, no_of_elements)
# Stop is inclusive
arr2 = np.linspace(10, 21, 100)
arr2

array([10.        , 10.11111111, 10.22222222, 10.33333333, 10.44444444,
       10.55555556, 10.66666667, 10.77777778, 10.88888889, 11.        ,
       11.11111111, 11.22222222, 11.33333333, 11.44444444, 11.55555556,
       11.66666667, 11.77777778, 11.88888889, 12.        , 12.11111111,
       12.22222222, 12.33333333, 12.44444444, 12.55555556, 12.66666667,
       12.77777778, 12.88888889, 13.        , 13.11111111, 13.22222222,
       13.33333333, 13.44444444, 13.55555556, 13.66666667, 13.77777778,
       13.88888889, 14.        , 14.11111111, 14.22222222, 14.33333333,
       14.44444444, 14.55555556, 14.66666667, 14.77777778, 14.88888889,
       15.        , 15.11111111, 15.22222222, 15.33333333, 15.44444444,
       15.55555556, 15.66666667, 15.77777778, 15.88888889, 16.        ,
       16.11111111, 16.22222222, 16.33333333, 16.44444444, 16.55555556,
       16.66666667, 16.77777778, 16.88888889, 17.        , 17.11111111,
       17.22222222, 17.33333333, 17.44444444, 17.55555556, 17.66

In [40]:
arr2 = np.linspace(1, 100, 100)
arr2

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [41]:
arr2.shape

(100,)

In [42]:
# Creating a 1-D array with all element 0 of shape (6, )
arr3 = np.zeros((6, ))
arr3

array([0., 0., 0., 0., 0., 0.])

In [45]:
# Creating a 2-D array with all element 0 of shape (4, 3)
arr4 = np.zeros((4, 3), dtype = int)
arr4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
# Creating a 1-D array with all element 1 of shape (6, )
arr5 = np.ones((6, ))
arr5

array([1., 1., 1., 1., 1., 1.])

In [46]:
# Creating a 2-D array with all element 1 of shape (6, 6)
arr6 = np.ones((6, 6))
arr6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [47]:
# Identity Array - Diaginal from top left to bottom right all are 1
# Rest all elements are zero
# No of rows and cols will always be same

arr7 = np.eye(6)
print(arr7)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [48]:
arr7 = np.eye(3, 4)
print(arr7)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [49]:
# Empty Array - []
arr8 = np.empty((5, 4))
arr8

# [[, , , ]]

array([[0. , 0. , 0.3, 1. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0. , 0. , 1. ],
       [0.5, 0. , 0. , 1. ]])

In [50]:
# Creating an array with random elements
arr9 = np.random.randint(10, 50, 70)
arr9

array([19, 25, 19, 10, 48, 49, 13, 25, 28, 16, 37, 19, 28, 10, 15, 14, 47,
       24, 42, 34, 47, 11, 48, 11, 22, 44, 16, 36, 40, 28, 25, 29, 19, 20,
       48, 20, 45, 43, 48, 18, 23, 42, 16, 37, 19, 44, 38, 42, 16, 37, 18,
       30, 24, 14, 46, 29, 38, 43, 41, 35, 35, 18, 22, 47, 13, 45, 27, 23,
       25, 43])

In [51]:
arr9.itemsize     # no of bytes taken by each element in the array.

8

In [52]:
arr9.dtype

dtype('int64')

## Changing the shape of an array

In [58]:
arr1 = np.random.randint(10, 70, 70)
arr1

array([13, 29, 43, 16, 17, 68, 36, 47, 68, 14, 67, 20, 10, 23, 11, 69, 13,
       61, 39, 35, 64, 68, 26, 28, 58, 50, 67, 23, 11, 19, 57, 27, 13, 24,
       18, 36, 36, 60, 26, 60, 42, 25, 10, 19, 62, 47, 51, 33, 14, 37, 62,
       23, 28, 37, 47, 50, 64, 47, 46, 40, 56, 14, 56, 39, 65, 45, 52, 51,
       14, 41])

In [54]:
arr1.shape

(70,)

In [55]:
# Reshape function does not make any changes to existing array
arr2 = arr1.reshape(10, 7)
arr2


array([[42, 51, 62, 52, 56, 57, 37],
       [64, 14, 28, 53, 29, 39, 19],
       [54, 45, 54, 19, 68, 66, 63],
       [57, 50, 62, 46, 25, 31, 45],
       [51, 61, 18, 14, 25, 33, 29],
       [28, 11, 53, 59, 52, 27, 31],
       [27, 65, 53, 26, 50, 34, 60],
       [58, 11, 25, 67, 55, 11, 12],
       [37, 63, 35, 61, 31, 61, 34],
       [40, 45, 11, 19, 54, 19, 51]])

In [56]:
arr1

array([42, 51, 62, 52, 56, 57, 37, 64, 14, 28, 53, 29, 39, 19, 54, 45, 54,
       19, 68, 66, 63, 57, 50, 62, 46, 25, 31, 45, 51, 61, 18, 14, 25, 33,
       29, 28, 11, 53, 59, 52, 27, 31, 27, 65, 53, 26, 50, 34, 60, 58, 11,
       25, 67, 55, 11, 12, 37, 63, 35, 61, 31, 61, 34, 40, 45, 11, 19, 54,
       19, 51])

While reshaping the array, no of elements in the original array and multiplication of dimension on reshaping should be equal, otherwise it will give ValueError

In [61]:
arr3 = np.random.randint(10, 70, 71)
arr3

array([28, 13, 56, 11, 51, 62, 14, 41, 28, 25, 59, 10, 43, 19, 20, 55, 23,
       49, 39, 62, 14, 26, 12, 24, 61, 40, 61, 47, 10, 63, 42, 13, 19, 16,
       17, 26, 17, 60, 13, 41, 15, 52, 17, 25, 44, 37, 46, 23, 39, 64, 61,
       53, 23, 26, 25, 15, 32, 11, 43, 68, 69, 24, 56, 61, 19, 19, 48, 44,
       13, 55, 11])

In [ ]:
[10, 20, 30, 40]
# [[10, 20, 30, 40]]  (1, 4)
[[10],
 [20],
 [30]
 [40]]           (4, 1)

In [63]:
# arr3.reshape(10, 7)
# arr3

In [64]:
arr3.reshape(1, 71)

array([[28, 13, 56, 11, 51, 62, 14, 41, 28, 25, 59, 10, 43, 19, 20, 55,
        23, 49, 39, 62, 14, 26, 12, 24, 61, 40, 61, 47, 10, 63, 42, 13,
        19, 16, 17, 26, 17, 60, 13, 41, 15, 52, 17, 25, 44, 37, 46, 23,
        39, 64, 61, 53, 23, 26, 25, 15, 32, 11, 43, 68, 69, 24, 56, 61,
        19, 19, 48, 44, 13, 55, 11]])

In [65]:
arr3.reshape(71, 1)

array([[28],
       [13],
       [56],
       [11],
       [51],
       [62],
       [14],
       [41],
       [28],
       [25],
       [59],
       [10],
       [43],
       [19],
       [20],
       [55],
       [23],
       [49],
       [39],
       [62],
       [14],
       [26],
       [12],
       [24],
       [61],
       [40],
       [61],
       [47],
       [10],
       [63],
       [42],
       [13],
       [19],
       [16],
       [17],
       [26],
       [17],
       [60],
       [13],
       [41],
       [15],
       [52],
       [17],
       [25],
       [44],
       [37],
       [46],
       [23],
       [39],
       [64],
       [61],
       [53],
       [23],
       [26],
       [25],
       [15],
       [32],
       [11],
       [43],
       [68],
       [69],
       [24],
       [56],
       [61],
       [19],
       [19],
       [48],
       [44],
       [13],
       [55],
       [11]])

In [78]:
# Reshaping using shape attribute
# reshape creates a new reshaped object where reshaping using shape attribute makes changes to existing object

arr1 = np.random.randint(10, 50, 100)
arr1

array([42, 39, 48, 44, 23, 39, 31, 32, 43, 27, 24, 34, 28, 43, 49, 46, 23,
       17, 15, 48, 22, 42, 10, 20, 26, 38, 32, 30, 12, 39, 39, 27, 20, 18,
       44, 46, 11, 14, 41, 47, 44, 33, 38, 13, 28, 31, 44, 17, 43, 45, 17,
       13, 32, 15, 10, 34, 14, 44, 24, 44, 35, 14, 21, 33, 17, 27, 23, 25,
       28, 19, 30, 19, 49, 18, 49, 11, 23, 22, 29, 28, 34, 30, 16, 17, 32,
       28, 49, 28, 49, 15, 37, 29, 32, 16, 46, 47, 27, 12, 20, 34])

In [79]:
arr2 = arr1
arr2

array([42, 39, 48, 44, 23, 39, 31, 32, 43, 27, 24, 34, 28, 43, 49, 46, 23,
       17, 15, 48, 22, 42, 10, 20, 26, 38, 32, 30, 12, 39, 39, 27, 20, 18,
       44, 46, 11, 14, 41, 47, 44, 33, 38, 13, 28, 31, 44, 17, 43, 45, 17,
       13, 32, 15, 10, 34, 14, 44, 24, 44, 35, 14, 21, 33, 17, 27, 23, 25,
       28, 19, 30, 19, 49, 18, 49, 11, 23, 22, 29, 28, 34, 30, 16, 17, 32,
       28, 49, 28, 49, 15, 37, 29, 32, 16, 46, 47, 27, 12, 20, 34])

In [ ]:
# 2D shape -> (row, col)
# 3D Shape -> (height, row, col)

In [80]:
arr2.shape = (2, 5, 10)
arr2

array([[[42, 39, 48, 44, 23, 39, 31, 32, 43, 27],
        [24, 34, 28, 43, 49, 46, 23, 17, 15, 48],
        [22, 42, 10, 20, 26, 38, 32, 30, 12, 39],
        [39, 27, 20, 18, 44, 46, 11, 14, 41, 47],
        [44, 33, 38, 13, 28, 31, 44, 17, 43, 45]],

       [[17, 13, 32, 15, 10, 34, 14, 44, 24, 44],
        [35, 14, 21, 33, 17, 27, 23, 25, 28, 19],
        [30, 19, 49, 18, 49, 11, 23, 22, 29, 28],
        [34, 30, 16, 17, 32, 28, 49, 28, 49, 15],
        [37, 29, 32, 16, 46, 47, 27, 12, 20, 34]]])

In [81]:
arr1

array([[[42, 39, 48, 44, 23, 39, 31, 32, 43, 27],
        [24, 34, 28, 43, 49, 46, 23, 17, 15, 48],
        [22, 42, 10, 20, 26, 38, 32, 30, 12, 39],
        [39, 27, 20, 18, 44, 46, 11, 14, 41, 47],
        [44, 33, 38, 13, 28, 31, 44, 17, 43, 45]],

       [[17, 13, 32, 15, 10, 34, 14, 44, 24, 44],
        [35, 14, 21, 33, 17, 27, 23, 25, 28, 19],
        [30, 19, 49, 18, 49, 11, 23, 22, 29, 28],
        [34, 30, 16, 17, 32, 28, 49, 28, 49, 15],
        [37, 29, 32, 16, 46, 47, 27, 12, 20, 34]]])

In [82]:
# Flattening of the array - Converting higher dimension array into single dinemnsion - ravel()

arr1

array([[[42, 39, 48, 44, 23, 39, 31, 32, 43, 27],
        [24, 34, 28, 43, 49, 46, 23, 17, 15, 48],
        [22, 42, 10, 20, 26, 38, 32, 30, 12, 39],
        [39, 27, 20, 18, 44, 46, 11, 14, 41, 47],
        [44, 33, 38, 13, 28, 31, 44, 17, 43, 45]],

       [[17, 13, 32, 15, 10, 34, 14, 44, 24, 44],
        [35, 14, 21, 33, 17, 27, 23, 25, 28, 19],
        [30, 19, 49, 18, 49, 11, 23, 22, 29, 28],
        [34, 30, 16, 17, 32, 28, 49, 28, 49, 15],
        [37, 29, 32, 16, 46, 47, 27, 12, 20, 34]]])

In [83]:
arr1.ravel()

array([42, 39, 48, 44, 23, 39, 31, 32, 43, 27, 24, 34, 28, 43, 49, 46, 23,
       17, 15, 48, 22, 42, 10, 20, 26, 38, 32, 30, 12, 39, 39, 27, 20, 18,
       44, 46, 11, 14, 41, 47, 44, 33, 38, 13, 28, 31, 44, 17, 43, 45, 17,
       13, 32, 15, 10, 34, 14, 44, 24, 44, 35, 14, 21, 33, 17, 27, 23, 25,
       28, 19, 30, 19, 49, 18, 49, 11, 23, 22, 29, 28, 34, 30, 16, 17, 32,
       28, 49, 28, 49, 15, 37, 29, 32, 16, 46, 47, 27, 12, 20, 34])

In [84]:
arr1

array([[[42, 39, 48, 44, 23, 39, 31, 32, 43, 27],
        [24, 34, 28, 43, 49, 46, 23, 17, 15, 48],
        [22, 42, 10, 20, 26, 38, 32, 30, 12, 39],
        [39, 27, 20, 18, 44, 46, 11, 14, 41, 47],
        [44, 33, 38, 13, 28, 31, 44, 17, 43, 45]],

       [[17, 13, 32, 15, 10, 34, 14, 44, 24, 44],
        [35, 14, 21, 33, 17, 27, 23, 25, 28, 19],
        [30, 19, 49, 18, 49, 11, 23, 22, 29, 28],
        [34, 30, 16, 17, 32, 28, 49, 28, 49, 15],
        [37, 29, 32, 16, 46, 47, 27, 12, 20, 34]]])

In [85]:
# Transpose of an array - rows to columns and vice versa

arr2.shape = (10, 10)
arr2

array([[42, 39, 48, 44, 23, 39, 31, 32, 43, 27],
       [24, 34, 28, 43, 49, 46, 23, 17, 15, 48],
       [22, 42, 10, 20, 26, 38, 32, 30, 12, 39],
       [39, 27, 20, 18, 44, 46, 11, 14, 41, 47],
       [44, 33, 38, 13, 28, 31, 44, 17, 43, 45],
       [17, 13, 32, 15, 10, 34, 14, 44, 24, 44],
       [35, 14, 21, 33, 17, 27, 23, 25, 28, 19],
       [30, 19, 49, 18, 49, 11, 23, 22, 29, 28],
       [34, 30, 16, 17, 32, 28, 49, 28, 49, 15],
       [37, 29, 32, 16, 46, 47, 27, 12, 20, 34]])

In [86]:
arr2.T

array([[42, 24, 22, 39, 44, 17, 35, 30, 34, 37],
       [39, 34, 42, 27, 33, 13, 14, 19, 30, 29],
       [48, 28, 10, 20, 38, 32, 21, 49, 16, 32],
       [44, 43, 20, 18, 13, 15, 33, 18, 17, 16],
       [23, 49, 26, 44, 28, 10, 17, 49, 32, 46],
       [39, 46, 38, 46, 31, 34, 27, 11, 28, 47],
       [31, 23, 32, 11, 44, 14, 23, 23, 49, 27],
       [32, 17, 30, 14, 17, 44, 25, 22, 28, 12],
       [43, 15, 12, 41, 43, 24, 28, 29, 49, 20],
       [27, 48, 39, 47, 45, 44, 19, 28, 15, 34]])

Arithmetic Operation on array


In [87]:
# Arithmetic Operators on array perfomrs the operation elementwise

arr1 = np.random.randint(10, 20, 10)
print(arr1)

[17 11 19 15 15 15 10 17 14 13]


In [88]:
# Mathematical Operations

print(arr1+5)
print(arr1-5)
print(arr1*5)
print(arr1/5)
print(arr1//5)
print(arr1%5)
print(arr1**5)

[22 16 24 20 20 20 15 22 19 18]
[12  6 14 10 10 10  5 12  9  8]
[85 55 95 75 75 75 50 85 70 65]
[3.4 2.2 3.8 3.  3.  3.  2.  3.4 2.8 2.6]
[3 2 3 3 3 3 2 3 2 2]
[2 1 4 0 0 0 0 2 4 3]
[1419857  161051 2476099  759375  759375  759375  100000 1419857  537824
  371293]


In [89]:
arr1

array([17, 11, 19, 15, 15, 15, 10, 17, 14, 13])

In [90]:
# Comparison operations
print(arr1>5)
print(arr1<5)
print(arr1<=5)
print(arr1>=5)
print(arr1==5)
print(arr1!=5)
print(arr1&5)     # It is performing bitwise operation

[ True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False]
[False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True]
[1 1 1 5 5 5 0 1 4 5]


In [94]:
# To perform these operation on the array, the dimension and shape of the array should remain same

arr1 = np.random.randint(10, 50, 5)
arr2 = np.random.randint(10, 90, 6)
print(arr1)
print(arr2)

[38 18 20 11 21]
[84 74 55 30 47 80]


In [95]:
# Arithmetic operations - element wise
print(arr2+arr1)
print(arr2-arr1)
print(arr2*arr1)
print(arr2/arr1)
print(arr2//arr1)
print(arr2%arr1)
print(arr2**arr1)

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [93]:
print(arr1 > arr2)
print(arr1 < arr2)
print(arr1 >= arr2)
print(arr1 <= arr2)
print(arr1 == arr2)
print(arr1 != arr2)
print(arr1 & arr2)

[ True False  True False False]
[False  True False  True  True]
[ True False  True False False]
[False  True False  True  True]
[False False False False False]
[ True  True  True  True  True]
[ 1  4  8  3 32]


In [96]:
# Vector product(dot product) - np.dot(arr1, arr2)
# No of elements in both the array shgould be same

print(arr1)
print()
print(arr2)

[38 18 20 11 21]

[84 74 55 30 47 80]


In [97]:
# np.dot(arr1, arr2)

ValueError: shapes (5,) and (6,) not aligned: 5 (dim 0) != 6 (dim 0)

In [98]:
arr1 = np.random.randint(11, 20, 10)
print(arr1)

[15 12 16 13 11 11 14 12 13 12]


In [99]:
arr2 = np.random.randint(21, 30, 10)
print(arr2)

[28 25 21 26 29 25 21 24 25 26]


In [100]:
np.dot(arr1, arr2)

np.int64(3207)

Understaing operations on 2D arrays

In [109]:
arr1 = np.random.randint(10, 30, 50).reshape(10, 5)
arr1

array([[21, 20, 23, 20, 23],
       [15, 29, 22, 13, 29],
       [22, 22, 22, 20, 26],
       [16, 19, 17, 10, 29],
       [14, 24, 20, 12, 14],
       [22, 27, 20, 27, 13],
       [17, 19, 14, 22, 19],
       [26, 15, 18, 17, 18],
       [16, 28, 26, 19, 17],
       [18, 23, 17, 21, 12]])

In [110]:
arr2 = np.random.randint(10, 70, 50).reshape(10, 5)
arr2

array([[31, 54, 60, 33, 65],
       [35, 63, 14, 69, 25],
       [52, 19, 36, 69, 52],
       [56, 29, 66, 36, 67],
       [68, 33, 26, 39, 56],
       [13, 52, 22, 23, 34],
       [61, 18, 13, 51, 54],
       [25, 50, 22, 61, 22],
       [10, 19, 38, 66, 23],
       [58, 21, 34, 30, 32]])

In [106]:
arr1+arr2

array([[51, 59, 35, 66, 91],
       [53, 74, 63, 72, 71],
       [40, 33, 78, 64, 69],
       [66, 89, 72, 35, 84],
       [64, 58, 29, 61, 74],
       [90, 39, 54, 65, 78],
       [38, 60, 66, 66, 39],
       [76, 84, 84, 79, 73],
       [28, 54, 64, 63, 44],
       [69, 44, 45, 36, 76]])

In [107]:
arr1 -= arr2       # arr1 = arr1-arr2
arr1

array([[-25, -13,  -7, -18, -43],
       [ -1, -42,  -5, -52, -39],
       [-20,  11, -24, -12, -35],
       [-16, -41, -46, -15, -54],
       [-12, -16,  -1, -33, -20],
       [-42,  -1,  -6, -39, -48],
       [ 16, -40, -38, -22,  -3],
       [-52, -26, -34, -53, -29],
       [ -2, -18, -22, -33, -20],
       [-43,   8,   7,  -8, -54]])

In [108]:
arr1 <= arr2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [111]:
# Unary operations on array - max, min, sum
print(np.max(arr1))

29


In [112]:
print(np.min(arr1))

10


In [113]:
print(np.sum(arr1))

993


In [114]:
print(np.mean(arr1))    # mean is average of all the values in arr1

19.86


In [115]:
arr1

array([[21, 20, 23, 20, 23],
       [15, 29, 22, 13, 29],
       [22, 22, 22, 20, 26],
       [16, 19, 17, 10, 29],
       [14, 24, 20, 12, 14],
       [22, 27, 20, 27, 13],
       [17, 19, 14, 22, 19],
       [26, 15, 18, 17, 18],
       [16, 28, 26, 19, 17],
       [18, 23, 17, 21, 12]])

In [116]:
np.max(arr1, axis = 0)      # look for max value along the column

array([26, 29, 26, 27, 29])

In [117]:
np.max(arr1, axis = 1)        # look for max value along the rows

array([23, 29, 26, 29, 24, 27, 22, 26, 28, 23])

In [ ]:
# Linear Algebra

In [124]:
# one doubt in regex quiz in portal sir. what will be output sir? what is .* and .* here sir?

import re
a='we arashfdjasf humans'
re.match(r'(.*)',a)

<re.Match object; span=(0, 21), match='we arashfdjasf humans'>